networks:
  swarm-net:
    external: true
    name: swarm-net

services:
  proxy:
    image: traefik:${TRAEFIK_VERSION:-v3.6.9}
    environment:
      - TRAEFIK_VERSION=${TRAEFIK_VERSION:-v3.6.9}
      - TRAEFIK_HOST=${TRAEFIK_HOST:-traefik.localhost}
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    configs:
      - source: TRAEFIK_STATIC
        target: /etc/traefik/traefik.yaml
      - source: TRAEFIK_DYNAMIC
        target: /etc/traefik/dynamic.yaml
    networks:
      - swarm-net
    secrets:
      - source: TRAEFIK_CREDENTIALS
        target: /etc/traefik/secrets/credentials
      - source: TRAEFIK_SENAI_CIMATEC_CRT
        target: /etc/traefik/certs/senaicimatec_com_br/senaicimatec_com_br.pem
      - source: TRAEFIK_SENAI_CIMATEC_KEY
        target: /etc/traefik/certs/senaicimatec_com_br/senaicimatec_com_br.key
      - source: TRAEFIK_JBTH_CRT
        target: /etc/traefik/certs/jbth/full_chain_jbth.crt
      - source: TRAEFIK_JBTH_KEY
        target: /etc/traefik/certs/jbth/jbth.com.br.key
      - source: TRAEFIK_UNIVERSIDADE_SENAI_CIMATEC_CRT
        target: /etc/traefik/certs/universidadesenaicimatec_edu_br/fullchain_universidadesenaicimatec.edu.brv2.pem
      - source: TRAEFIK_UNIVERSIDADE_SENAI_CIMATEC_KEY
        target: /etc/traefik/certs/universidadesenaicimatec_edu_br/universidadesenaicimatec.edu.brv2.key
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=swarm-net"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"

        ## Dashboard
        - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_HOST:-traefik.localhost}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
        - "traefik.http.routers.dashboard.entrypoints=websecure"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.routers.dashboard.tls=true"
        - "traefik.http.routers.dashboard.middlewares=basic-auth@swarm"

        ## Metrics
        - "traefik.http.routers.metrics.rule=Host(`${TRAEFIK_HOST:-traefik.localhost}`) && PathPrefix(`/metrics`)"
        - "traefik.http.routers.metrics.entrypoints=websecure"
        - "traefik.http.routers.metrics.service=prometheus@internal"
        - "traefik.http.routers.metrics.tls=true"
        - "traefik.http.routers.metrics.middlewares=basic-auth@swarm"

        ## Middlewares
        - "traefik.http.middlewares.basic-auth.basicauth.usersFile=/etc/traefik/secrets/credentials"

secrets:
  TRAEFIK_SENAI_CIMATEC_CRT:
    external: true
  TRAEFIK_SENAI_CIMATEC_KEY:
    external: true
  TRAEFIK_JBTH_CRT:
    external: true
  TRAEFIK_JBTH_KEY:
    external: true
  TRAEFIK_UNIVERSIDADE_SENAI_CIMATEC_CRT:
    external: true
  TRAEFIK_UNIVERSIDADE_SENAI_CIMATEC_KEY:
    external: true
  TRAEFIK_CREDENTIALS:
    external: true

configs:
  TRAEFIK_DYNAMIC:
    external: true
  TRAEFIK_STATIC:
    external: true
