networks:
  swarm-net:
    external: true
    name: swarm-net

services:
  proxy:
    image: traefik:${TRAEFIK_VERSION}
    restart: always
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml
      - ./config/dynamic.yaml:/etc/traefik/dynamic.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    secrets:
      - source: TRAEFIK_CREDENTIALS
        target: /etc/traefik/secrets/credentials
      - source: TRAEFIK_SENAICIMATEC_CRT
        target: /etc/traefik/certs/senaicimatec_com_br/senaicimatec_com_br.pem
      - source: TRAEFIK_SENAICIMATEC_KEY
        target: /etc/traefik/certs/senaicimatec_com_br/senaicimatec_com_br.key
      - source: TRAEFIK_JBTH_CRT
        target: /etc/traefik/certs/jbth/full_chain_jbth.crt
      - source: TRAEFIK_JBTH_KEY
        target: /etc/traefik/certs/jbth/jbth.com.br.key
      - source: TRAEFIK_UNIVERSIDADESENAICIMATEC_CRT
        target: /etc/traefik/certs/universidadesenaicimatec_edu_br/fullchain_universidadesenaicimatec.edu.brv2.pem
      - source: TRAEFIK_UNIVERSIDADESENAICIMATEC_KEY
        target: /etc/traefik/certs/universidadesenaicimatec_edu_br/universidadesenaicimatec.edu.brv2.key
      - source: TRAEFIK_CREDENTIALS
        target: /etc/traefik/secrets/credentials
      - source: TRAEFIK_SENAICIMATEC_CRT
        target: /etc/traefik/certs/senaicimatec_com_br/senaicimatec_com_br.pem
      - source: TRAEFIK_SENAICIMATEC_KEY
        target: /etc/traefik/certs/senaicimatec_com_br/senaicimatec_com_br.key
      - source: TRAEFIK_JBTH_CRT
        target: /etc/traefik/certs/jbth/full_chain_jbth.crt
      - source: TRAEFIK_JBTH_KEY
        target: /etc/traefik/certs/jbth/jbth.com.br.key
      - source: TRAEFIK_UNIVERSIDADESENAICIMATEC_CRT
        target: /etc/traefik/certs/universidadesenaicimatec_edu_br/fullchain_universidadesenaicimatec.edu.brv2.pem
      - source: TRAEFIK_UNIVERSIDADESENAICIMATEC_KEY
        target: /etc/traefik/certs/universidadesenaicimatec_edu_br/universidadesenaicimatec.edu.brv2.key
    networks:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=swarm-net"

      ## Dashboard
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_HOST}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.middlewares=basic-auth@file"

      ## Metrics
      - "traefik.http.routers.metrics.rule=Host(`${TRAEFIK_HOST}`) && PathPrefix(`/metrics`)"
      - "traefik.http.routers.metrics.entrypoints=websecure"
      - "traefik.http.routers.metrics.service=prometheus@internal"
      - "traefik.http.routers.metrics.tls=true"
      - "traefik.http.routers.metrics.middlewares=basic-auth@file"

secrets:
  TRAEFIK_SENAICIMATEC_CRT:
    file: ./certs/senaicimatec_com_br/senaicimatec_com_br.pem
  TRAEFIK_SENAICIMATEC_KEY:
    file: ./certs/senaicimatec_com_br/senaicimatec_com_br.key
  TRAEFIK_JBTH_CRT:
    file: ./certs/jbth/full_chain_jbth.crt
  TRAEFIK_JBTH_KEY:
    file: ./certs/jbth/jbth.com.br.key
  TRAEFIK_UNIVERSIDADESENAICIMATEC_CRT:
    file: ./certs/universidadesenaicimatec_edu_br/fullchain_universidadesenaicimatec.edu.brv2.pem
  TRAEFIK_UNIVERSIDADESENAICIMATEC_KEY:
    file: ./certs/universidadesenaicimatec_edu_br/universidadesenaicimatec.edu.brv2.key
  TRAEFIK_CREDENTIALS:
    file: ./config/credentials
