# traefik.yml
api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/etc/traefik/certs/_wildcard.localhost.com+2.pem"
        keyFile: "/etc/traefik/certs/_wildcard.localhost.com+2-key.pem"

providers:
  docker:
    exposedByDefault: false